[#IOCOM-1214] init migration rp-example
pagopa/io-fims pull request #19
Opened 2024-04-03 09:02 UTC by acuiuli

### List of changes
- [init migration rp-example](https://github.com/pagopa/io-fims/commit/dac8efee2b14a57b4e5fb8401af7c80d6a390ded)

### Motivation and context

This is the init of the migration of the rp-example app into the monorepo io-fims

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-04-03 09:51 UTC, lucacavallaro commented
Can you better describe the purpose of this PR? What does it introduce? What changes have you made?

2024-04-03 12:21 UTC, Garma00 requested changes

2024-04-03 12:21 UTC, Garma00 commented on apps/openid-rp-example-app/.dockerignore
> +**/node_modules/
I think we can remove this ignore since we are not using `node_modules` anymore

2024-04-03 12:21 UTC, Garma00 commented on apps/openid-rp-example-app/.eslintrc.js
> +    "node_modules",
Ditto

2024-04-03 12:21 UTC, Garma00 commented on apps/openid-rp-example-app/dist/package.json
I think we don't want to commit the `dist/` directory

2024-04-04 13:14 UTC, Garma00 submitted a review, later dismissed

2024-04-08 11:04 UTC, lucacavallaro requested changes

2024-04-08 11:04 UTC, lucacavallaro commented on apps/relying-party-func/dist/CreateOIDCClientConfig.js
@acuiuli can you remove this files! I don't know why they are committed :)

2024-04-08 11:05 UTC, lucacavallaro commented
@acuiuli you should align this branch with `main` and remove the `dist` folder you committed, and for me it's ok for merge

2024-04-08 12:45 UTC, lucacavallaro approved these changes

2024-04-08 12:47 UTC, merged