feat(op-func): Add new queue trigger function CreateOIDCClient
pagopa/io-fims pull request #39
Opened 2024-04-23 14:16 UTC by Garma00

### List of changes

* Add a new cosmos collection clients;
* Add a new function that reads client-config from the queue and write the client in the new cosmos collection;
* Add new client schema.

### Motivation and context

We need a way to save OIDCClient readed ad parsed from the queue client-config in the new cosmos collection clients so we are adding this queue trigger function.

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [x] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-04-30 09:08 UTC, lucacavallaro requested changes

2024-04-30 09:08 UTC, lucacavallaro commented on apps/op-func/vitest.config.js.timestamp-1713344639102-ee3cfe5e7b323.mjs
i think this file should be removed

2024-05-02 09:13 UTC, Garma00 commented on apps/op-func/vitest.config.js.timestamp-1713344639102-ee3cfe5e7b323.mjs
[a57d360](https://github.com/pagopa/io-fims/pull/39/commits/a57d3608b8d51ec670ca3048c31d0a579439149c)

2024-05-02 09:41 UTC, lucacavallaro approved these changes

2024-05-06 16:38 UTC, merged