feat: add access management function
pagopa/io-fims pull request #74
Opened 2024-10-31 08:28 UTC by lucacavallaro

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-11-14 15:02 UTC, Garma00 requested changes
there are some funcitons defined with the `function` keyword instead of using arrow functions, is there any reason? I would prefer to follow a standard

2024-11-15 09:23 UTC, lucacavallaro commented on apps/user-func/src/adapters/functions/get-access-history.ts
> +function decodeHttpRequest(
why do prefer an arrow function? they are essentially the same

2024-11-15 09:23 UTC, lucacavallaro commented on apps/user-func/src/adapters/functions/tests/create-access.spec.ts
> +  it.each([{}, { fiscalCode: "not-valid" }])(
because we are checking to the cases, one with empty object (`{}`) and one with `{ fiscalCode: "..." }`

2024-11-15 09:24 UTC, lucacavallaro commented on apps/user-func/tsconfig.json
> +    "skipLibCheck": true
yes, without this flag, tsc will try to check types for `@pagopa/io-functions-commons` (that are broken)

2024-11-15 09:28 UTC, Garma00 commented on apps/user-func/src/adapters/functions/get-access-history.ts
> +function decodeHttpRequest(
I would prefer to maintain a standard but it's just a consideration

2024-11-15 11:25 UTC, lucacavallaro commented on apps/user-func/src/adapters/functions/get-access-history.ts
> +function decodeHttpRequest(
done https://github.com/pagopa/io-fims/pull/74/commits/4a1b7e6a96c57b5c5114f608a6d88075ec9440ad

2024-11-15 12:35 UTC, Garma00 approved these changes

2024-11-15 13:28 UTC, merged